behaviors:
  RobotWave:
    hyperparameters:
      batch_size: 64
      beta: 0.03
      buffer_size: 1024
      epsilon: 0.3
      lambd: 0.95
      learning_rate: 0.0001
      learning_rate_schedule: linear
      num_epoch: 3
    keep_checkpoints: 1
    max_steps: 10000
    network_settings:
      hidden_units: 256
      memory:
        memory_size: 128
        sequence_length: 64
      normalize: false
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    summary_freq: 500
    time_horizon: 64
    trainer_type: ppo
